# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GreetingService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15GreetingService.proto\"\x06\n\x04Null\":\n\x06\x46light\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x11\n\tcity_from\x18\x02 \x01(\t\x12\x0f\n\x07\x63ity_to\x18\x03 \x01(\t\"+\n\x0c\x43onfirmation\x12\x1b\n\x13is_flight_available\x18\x01 \x01(\x08\x32\x34\n\rFlightService\x12#\n\tgetFlight\x12\x07.Flight\x1a\r.Confirmationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GreetingService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=25
  _NULL._serialized_end=31
  _FLIGHT._serialized_start=33
  _FLIGHT._serialized_end=91
  _CONFIRMATION._serialized_start=93
  _CONFIRMATION._serialized_end=136
  _FLIGHTSERVICE._serialized_start=138
  _FLIGHTSERVICE._serialized_end=190
# @@protoc_insertion_point(module_scope)
